// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PriceObservation struct {
	ID           int64
	InstrumentID uuid.UUID
	Currency     string
	MinorUnits   int64
	ObservedAt   pgtype.Timestamptz
}
