// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listByInstrument = `-- name: ListByInstrument :many
SELECT id, instrument_id, currency, minor_units, observed_at FROM price_observations WHERE instrument_id = $1
ORDER BY observed_at, id
`

func (q *Queries) ListByInstrument(ctx context.Context, instrumentID uuid.UUID) ([]PriceObservation, error) {
	rows, err := q.db.Query(ctx, listByInstrument, instrumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceObservation{}
	for rows.Next() {
		var i PriceObservation
		if err := rows.Scan(
			&i.ID,
			&i.InstrumentID,
			&i.Currency,
			&i.MinorUnits,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const save = `-- name: Save :exec
INSERT INTO price_observations (instrument_id, currency, minor_units, observed_at)
VALUES ($1, $2, $3, $4)
`

type SaveParams struct {
	InstrumentID uuid.UUID
	Currency     string
	MinorUnits   int64
	ObservedAt   pgtype.Timestamptz
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save,
		arg.InstrumentID,
		arg.Currency,
		arg.MinorUnits,
		arg.ObservedAt,
	)
	return err
}
