// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/google/uuid"
)

type CashBalance struct {
	AccountID  uuid.UUID
	Currency   string
	MinorUnits int64
}
