// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const listByAccount = `-- name: ListByAccount :many
SELECT account_id, currency, minor_units FROM cash_balances WHERE account_id = $1 ORDER BY currency
`

func (q *Queries) ListByAccount(ctx context.Context, accountID uuid.UUID) ([]CashBalance, error) {
	rows, err := q.db.Query(ctx, listByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CashBalance{}
	for rows.Next() {
		var i CashBalance
		if err := rows.Scan(&i.AccountID, &i.Currency, &i.MinorUnits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const save = `-- name: Save :exec
INSERT INTO cash_balances (account_id, currency, minor_units) VALUES ($1, $2, $3)
ON CONFLICT (account_id, currency) DO UPDATE SET minor_units = EXCLUDED.minor_units
`

type SaveParams struct {
	AccountID  uuid.UUID
	Currency   string
	MinorUnits int64
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save, arg.AccountID, arg.Currency, arg.MinorUnits)
	return err
}
