// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const listByAccount = `-- name: ListByAccount :many
SELECT account_id, instrument_id, quantity FROM positions WHERE account_id = $1 ORDER BY instrument_id
`

func (q *Queries) ListByAccount(ctx context.Context, accountID uuid.UUID) ([]Position, error) {
	rows, err := q.db.Query(ctx, listByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(&i.AccountID, &i.InstrumentID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const save = `-- name: Save :exec
INSERT INTO positions (account_id, instrument_id, quantity) VALUES ($1, $2, $3)
ON CONFLICT (account_id, instrument_id) DO UPDATE SET quantity = EXCLUDED.quantity
`

type SaveParams struct {
	AccountID    uuid.UUID
	InstrumentID uuid.UUID
	Quantity     decimal.Decimal
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save, arg.AccountID, arg.InstrumentID, arg.Quantity)
	return err
}
