// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const findByID = `-- name: FindByID :one
SELECT id, name FROM accounts WHERE id = $1
`

func (q *Queries) FindByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, findByID, id)
	var i Account
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const list = `-- name: List :many
SELECT id, name FROM accounts ORDER BY id
`

func (q *Queries) List(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const save = `-- name: Save :exec
INSERT INTO accounts (id, name) VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name
`

type SaveParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save, arg.ID, arg.Name)
	return err
}
