// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/google/uuid"
)

type Property struct {
	ID         uuid.UUID
	Name       string
	Currency   string
	MinorUnits int64
}
