// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const create = `-- name: Create :exec
INSERT INTO properties (id, name, currency, minor_units) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name,
    currency = EXCLUDED.currency, minor_units = EXCLUDED.minor_units
`

type CreateParams struct {
	ID         uuid.UUID
	Name       string
	Currency   string
	MinorUnits int64
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.Exec(ctx, create,
		arg.ID,
		arg.Name,
		arg.Currency,
		arg.MinorUnits,
	)
	return err
}

const list = `-- name: List :many
SELECT id, name, currency, minor_units FROM properties ORDER BY id
`

func (q *Queries) List(ctx context.Context) ([]Property, error) {
	rows, err := q.db.Query(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Property{}
	for rows.Next() {
		var i Property
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.MinorUnits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceValue = `-- name: ReplaceValue :one
UPDATE properties SET currency = $2, minor_units = $3 WHERE id = $1 RETURNING id, name, currency, minor_units
`

type ReplaceValueParams struct {
	ID         uuid.UUID
	Currency   string
	MinorUnits int64
}

func (q *Queries) ReplaceValue(ctx context.Context, arg ReplaceValueParams) (Property, error) {
	row := q.db.QueryRow(ctx, replaceValue, arg.ID, arg.Currency, arg.MinorUnits)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.MinorUnits,
	)
	return i, err
}
