// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/google/uuid"
)

type Instrument struct {
	ID            uuid.UUID
	Kind          string
	Symbol        string
	Name          string
	QuoteCurrency string
}
