// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const findByID = `-- name: FindByID :one
SELECT id, kind, symbol, name, quote_currency FROM instruments WHERE id = $1
`

func (q *Queries) FindByID(ctx context.Context, id uuid.UUID) (Instrument, error) {
	row := q.db.QueryRow(ctx, findByID, id)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Symbol,
		&i.Name,
		&i.QuoteCurrency,
	)
	return i, err
}

const list = `-- name: List :many
SELECT id, kind, symbol, name, quote_currency FROM instruments ORDER BY id
`

func (q *Queries) List(ctx context.Context) ([]Instrument, error) {
	rows, err := q.db.Query(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Instrument{}
	for rows.Next() {
		var i Instrument
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Symbol,
			&i.Name,
			&i.QuoteCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const save = `-- name: Save :exec
INSERT INTO instruments (id, kind, symbol, name, quote_currency) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET kind = EXCLUDED.kind, symbol = EXCLUDED.symbol,
    name = EXCLUDED.name, quote_currency = EXCLUDED.quote_currency
`

type SaveParams struct {
	ID            uuid.UUID
	Kind          string
	Symbol        string
	Name          string
	QuoteCurrency string
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save,
		arg.ID,
		arg.Kind,
		arg.Symbol,
		arg.Name,
		arg.QuoteCurrency,
	)
	return err
}
